- set_fact:
    all_dotfiles_items: "{{ dotfiles_items + additional_dotfiles_items }}"

- name: Install the dotfiles
  get_url:
    url: "{{dotfiles_repo}}/{{ item }}"
    dest: "~/{{ item }}"
  with_items: "{{ all_dotfiles_items }}"
  when: dotfiles_install == True
