- set_fact:
    all_brew_base_items: "{{ brew_base_items + additional_brew_base_items }}"
  tags: 
    - homebrew
    - custom_vars

- set_fact:
    all_brew_cask_items: "{{ brew_cask_items + additional_brew_cask_items }}"
  tags:
    - homebrew
    - homebrew-cask  
    - custom_vars
   
- name: Check if Homebrew is already installed
  stat:
    path: "{{ homebrew_path }}/brew"
  register: b
  tags: homebrew

- name: Install Homebrew
  script: install_homebrew.sh
  when: not b.stat.exists
  tags:
    - homebrew
    - homebrew-cask

- name: Ensure Homebrew is in our path
  ansible.builtin.lineinfile:
    path: ~/.bash_profile 
    regexp: 'PATH={{ homebrew_path }}:$PATH'
    insertafter: 'PATH=$HOME/bin:$PATH'
    line: "PATH={{ homebrew_path }}:$PATH"

- name: Install base things from brew
  homebrew:
    name: "{{ all_brew_base_items }}"
  register: result
  tags:
    - homebrew
    - homebrew-cask

- name: Install cask things from brew
  homebrew_cask:
    name: "{{ all_brew_cask_items }}"
    accept_external_apps: True  
  tags:
    - homebrew
    - homebrew_cask
    - cask_only
