- set_fact:
    all_brew_base_items: "{{ brew_base_items + additional_brew_base_items }}"
  tags: homebrew

- set_fact:
    all_brew_cask_items: "{{ brew_cask_items + additional_brew_cask_items }}"
  tags:
    - homebrew
    - homebrew-cask  

- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: b
  tags: homebrew

- name: Install Homebrew
  script: install_homebrew.sh
  when: not b.stat.exists
  tags:
    - homebrew
    - homebrew-cask

- name: Install base things from brew
  homebrew:
    #name: "{{item}}"
    name: "{{ all_brew_base_items }}"
  #with_items: "{{ all_brew_base_items }}"
  ignore_errors: true
  tags:
    - homebrew
    - homebrew-cask

- name: Install cask things from brew
  homebrew_cask:
    #name: "{{item}}"
    name: "{{ all_brew_cask_items }}"
  #with_items: "{{ all_brew_cask_items }}"
  ignore_errors: true
  tags:
    - homebrew
    - homebrew_cask
