- name: install kubectl versions
  get_url: 
    url: "https://dl.k8s.io/release/v{{ item }}/bin/darwin/amd64/kubectl"
    dest: "/usr/local/bin/kubectl-{{ item }}"
    mode: +x
  loop: "{{ kubectl_versions }}"
  loop_control:
    label: "{{ item }}"
  when: kubectl_versions is defined 
  tags:
    - kubectl

- name: Set default kubectl
  file:
    src: "/usr/local/bin/kubectl-{{ kubectl_default_version }}"
    dest: "/usr/local/bin/kubectl"
    state: link
  when: kubectl_default_version is defined
  tags:
    - kubectl

- name: Make ~/.kuberc 
  template:
    src: kuberc 
    dest: "~/.kuberc"
  tags:
    - kubectl

- name: Add the kubectl completion script to /usr/local/etc/bash_completion.d 
  shell: "kubectl completion bash >/usr/local/etc/bash_completion.d/kubectl"
  tags: 
    - kubectl