- name: see if we already have our vault binary version installed
  stat:
    path: "{{ homebrew_path }}/vault-{{ release }}"
  register: vault_binary
  tags:
    - vault

- block:
  - name: "Install Vault version {{ release }}"
    ansible.builtin.unarchive: 
      src: "https://releases.hashicorp.com/vault/{{ release }}/vault_{{ release }}_darwin_amd64.zip"
      dest: "/tmp"
      remote_src: yes

  - name: "Move vault binary {{ release }} to {{ homebrew_path }}/vault-{{ release }}"
    shell: "mv /tmp/vault {{ homebrew_path }}/vault-{{ release }}"

  when: 
    - vault_versions is defined 
    - not vault_binary.stat.exists
  tags:
    - vault

- name: see if we already have our default vault binary version installed
  stat:
    path: "{{ homebrew_path }}/vault-{{ vault_default_version }}"
  register: vault_default_binary
  tags:
    - vault
